### ISSUE TITLE
about the result

### ISSUE THREAD

**Issue by Gavin666Github** [zhangchbin/evaluation-for-shadow-detection#1]
I run the code ,but got the result not so good ，What is the result of your test?
here is my test:
![image](https://user-images.githubusercontent.com/35061171/65752852-44cdb800-e140-11e9-8f06-a8328d337365.png)

**Comment by zhangchbin** [comment]
> I run the code ,but got the result not so good ，What is the result of your test?
> here is my test:
> ![image](https://user-images.githubusercontent.com/35061171/65752852-44cdb800-e140-11e9-8f06-a8328d337365.png)

Thanks for your attention. I have checked the code using my previous result, it is okay.
Note, is there any difference between the name of gt and result?

**Comment by Gavin666Github** [comment]
> > I run the code ,but got the result not so good ，What is the result of your test?
> > here is my test:
> > ![image](https://user-images.githubusercontent.com/35061171/65752852-44cdb800-e140-11e9-8f06-a8328d337365.png)
> 
> Thanks for your attention. I have checked the code using my previous result, it is okay.
> Note, is there any difference between the name of gt and result?

@zhangchbin the file folder name is different ,but the name of the file in these two folders is the same ,eg: if there is image like xxx/Image_001.jpg then it exist file yyy/Image_001.jpg，xxx and yyy  are folders

**Comment by zhangchbin** [comment]
> > > I run the code ,but got the result not so good ，What is the result of your test?
> > > here is my test:
> > > ![image](https://user-images.githubusercontent.com/35061171/65752852-44cdb800-e140-11e9-8f06-a8328d337365.png)
> > 
> > 
> > Thanks for your attention. I have checked the code using my previous result, it is okay.
> > Note, is there any difference between the name of gt and result?
> 
> @zhangchbin the file folder name is different ,but the name of the file in these two folders is the same ,eg: if there is image like xxx/Image_001.jpg then it exist file yyy/Image_001.jpg，xxx and yyy are folders

Yes, it is right ... you can send the image and gt to my email: zhangchbin AT gmail DOT com, I will test it.

**Comment by Gavin666Github** [comment]
@zhangchbin i have sent it to you ,check it please ,thank you!

**Comment by zhangchbin** [comment]
> @zhangchbin i have sent it to you ,check it please ,thank you!

I have test your result, it shows as:

python main.py --result_dir '../sbu_prediction_3001/' --gt_dir '../../data/SBU/Imgs/'
ber =  tensor(4.1968)
p_error =  tensor(5.7295)
n_error =  tensor(2.6642)
acc_final =  tensor(96.7378)

**Comment by Gavin666Github** [comment]
> > @zhangchbin i have sent it to you ,check it please ,thank you!
> 
> I have test your result, it shows as:
> 
> python main.py --result_dir '../sbu_prediction_3001/' --gt_dir '../../data/SBU/Imgs/'
> ber = tensor(4.1968)
> p_error = tensor(5.7295)
> n_error = tensor(2.6642)
> acc_final = tensor(96.7378)

yeah,it  looks normal. I'll check it again and try it again，thks
